### PR TITLE
Adding Popmotion example

### PR DESCRIPTION
**Pull request by InventingWithMonster**

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey, thanks for the PR! I've been meaning to get Popmotion added to this at some point. 😄 

The code looks great at a glance. Most of the other libraries are pulled in via CDN... having a local copy works too, but it's hard to tell which version of popmotion this is, and know when to update it. If we aren't pulling in the library via CDN, can we add a version number to the file name or a comment or something?

Other than that, I should be able to test this out later this week. 👍

**Comment by InventingWithMonster** [comment]
Good point, I was just copying one of the other dirs but this makes more sense. I've updated it with a CDN reference!

**Comment by bryanbraun** [comment]
This looks good. It looks like you accidentally deleted the wrong file in that latest commit, but no worries. I've swapped it back in and tested it locally and it all looks great, so I'll just add that commit on top.

Thanks again for the contribution. This makes 19 examples! 🙌

**Comment by InventingWithMonster** [comment]
Thanks man sorry for the fuck up!

**Pull request merged**
