### PR TITLE
Demo using React

### PR DESCRIPTION
**Pull request by rajington**
This demo answers #19 and uses plain React instead of React-Motion which isn't really applicable.

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey @rajington, I just got to looking at this now, and WOW, this is really great! I'm excited to include it.

Just two things:
1. Could you rebase this? I merged a bunch of other code and now this has conflicts with master. 😢 
2. Can we add something to that readme that talks briefly about react? Here's what I have in mind... feel free to add to it, or just dump it into the README as-is:

```
# React
React.js is a javascript library for building user interfaces. It allows developers to build encapsulated components that manage their own state, and then compose them to make complex UIs.

React doesn't explicitly provide animation functionality, but since React is popular and questions about animating in React often arise, this demo is instructive. Supporting tools like ReactMotion provide additional functionality for animations, though this demo doesn't use it.

## Project Links
- [React Github Repo](https://github.com/facebook/react)
- [React Community Github Org (containing supporting projects)](https://github.com/reactjs)
- [React Website & Docs](https://facebook.github.io/react/)

## Resources
- [React: Getting Started](https://facebook.github.io/react/docs/getting-started.html)
- [Awesome React: A collection of awesome things regarding the React ecosystem.](https://github.com/enaqx/awesome-react)

```

Thanks again!

**Comment by rajington** [comment]
absolutely, i'll submit a new PR

**Comment by bryanbraun** [comment]
Merged. Thanks again!

**Comment by rajington** [comment]
Not the best place for this but gives you the most context... just wanted to say that I saw your talk yesterday at Fluent, great job! Had to run but thanks again for making this project and submitting it to Hacktobefest. I'm not _really_ sure how useful React is as an example, at least in it's current implementation, don't worry about hurting my feelings if you feel you need to drop it.

**Comment by bryanbraun** [comment]
@rajington, it was great chatting with you at Fluent.

Yeah, I still like the demo, even if it is a bit different than the others. Maybe one day I'll build out a separate part of the site for these "framework" type of demos ([more details here](https://github.com/sparkbox/bouncy-ball/pull/36#issuecomment-277353498)), but I'm comfortable leaving this one in here for now.

**Pull request merged**
