### PR TITLE
Add MP4 in <img> example

### PR DESCRIPTION
**Pull request by tigt**
See Issue #58

### CODE REVIEW

**Comment by bryanbraun** [comment]
Wow great find @tigt. I hope Cincinnati has been treating you well. 😄

The only improvement I can think of is using the "pink" color ball so it matches the color of the other animated images. There's a source `bouncy-ball.mov` file for the pink ball in `https://github.com/sparkbox/bouncy-ball/tree/master/examples/animated-gif/build-files`. Any chance you can convert that to mp4 and use it as the source file instead?

FYI, I'm digging the code comments you added here. 💪

**Comment by bryanbraun** [comment]
Hey so, I'm just gonna go ahead and merge this, since it's pretty much there. I might push up another commit using the pink ball video soon.

Thanks for the contribution. 👍

**Comment by tigt** [comment]
Ah, my bad. I shouldn’t have responded over email, since my mail server is still having some issues.

I’ll open a new MR with the corrected color soon.

**Comment by bryanbraun** [comment]
Not necessary... I took care of it in 3fbe372beb6efe93ea02c937412b3e0fad8d926d . 👍

**Pull request merged**
