### PR TITLE
Updated gsap.min.js to version 3.5.1

### PR DESCRIPTION
**Pull request by ishanarya0**

### CODE REVIEW

**Comment by bryanbraun** [comment]
Hey @ishanarya0, this is working great but could you change the file name from `gsap.min.js` to `gsap-3.5.1.min.js`? I [mentioned it in the issue](https://github.com/sparkbox/bouncy-ball/issues/78#issue-708265651) but it's easy to miss. 😄

**Comment by ishanarya0** [comment]
Oh, my bad! I missed that. Updated the name now.

**Comment by bryanbraun** [comment]
@ishanarya0, thanks. I think it'll need to be updated [in the html file too](https://github.com/sparkbox/bouncy-ball/blob/master/examples/greensock/index.html#L20). 😅

**Comment by ishanarya0** [comment]
Extremely sorry for the trouble @bryanbraun 😐

**Review by bryanbraun — APPROVED** [review]
It's working great!

**Pull request merged**
